config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/posts/new' => 'posts#new'
	 post '/posts' => 'posts#create', as: :posts
	  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'posts#index'
	get '/posts/:id' => 'posts#show', as: 'post'
	get '/post/top' => 'posts#top'

	##page.htmlをリンク先に指定したい場合
	get "/post/page" => "posts#page"
	get "/post/omichi" => "posts#omichi"
	get "/post/taiki" => "posts#taiki"
	get "/post/taihei" => "posts#taihei"
	get "/post/hikaru" => "posts#hikaru"
	get "/post/fuku" => "posts#fuku"
	get "/post/song" => "posts#song"
	get "/post/history" => "posts#history"
	get "/post/nana" => "posts#nana"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: { message: "タイトルをいれないの？？"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   before_action :authenticate_user!,only: [:new,:create]
  def new
  	@post = Post.new
  end

  def create 
  	@post = Post.new
  	@post.title = params[:title]
  	@post.body = params[:body]
  	if @post.save
  	   redirect_to root_path
    else 
      render 'new'
    end
  end
def index
  @posts = Post.all.order("id DESC")
  
end
def show
@post = Post.find(params[:id])
end

def top
end

#page.htmlっていうページへのリンク先を作りたい場合
def page
  render :layout => false
end

def omichi
  render :layout => false
end

def taiki
  render :layout => false
end

def hikaru
  render :layout => false
end

def taihei
  render :layout => false
end

def song
  render :layout => false
end

def history
  render :layout => false
end

def fuku
  render :layout => false
end

def nana
  render :layout => false
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ターミナルfun</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div id="intro">
  <!-- コンテンツ -->
      <div class="check">
        
        <p><h1>TERM-INAL</h1> </p>


        <p> <%= link_to "TAIKI","/post/taiki" %> /<%= link_to "OMICHI",post_omichi_path %>/<%= link_to "TAIHEI","/post/taihei" %> /<%= link_to "HIKARU","/post/hikaru" %> /<%= link_to "ヒストリー","/post/history" %> /<%= link_to "レッスン曲","/post/song" %> /<%= link_to "服装","/post/fuku" %> 
        </p>

        <% if user_signed_in? %>
          Logged in as <%= current_user.email %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "loginlink" %>
        <% else %>
          <%= link_to "メンバー専用", new_user_registration_path,class: "loginlink" %> |
          <%= link_to "ログイン", new_user_session_path, class: "loginlink" %>
        <% end %>

      </div>
      <div class="koushin">
        <h1>出演イベント他</h1>

        <div class="embeded">
          <%= yield %>
        </div>
      </div>
      
    </div>
    <div id="second">
      <!-- コンテンツ -->
       <section class="clearfix btn-sec">
             <div class="text-box">
                 <button type="" class="btn add-btn1">
                 トレーニングメニュー
                 </button>
                 <li class="text1 text"></li>
             </div>
             <div class="text-box">
              <button type="" class="btn add-btn2">
                 今日のあなたは
                 </button>
                 <li class="text2 text"></li>
             </div>
             <div class="text-box">
                 <button type="" class="btn add-btn3">
                 回数
                 </button>
                 <li class="text3 text"></li>
             </div>
             <div class="text-box">
                 <button type="" class="btn add-btn4">
                 メンバーの誰にする？
                 </button>
                 <li class="text4 text"></li>
             </div>
             <div class="text-box">
                 <button type="" class="btn add-btn5">
                 意識するところ？
                 </button>
                 <li class="text5 text"></li>
             </div>
             <div class="text-box">
                 <button type="" class="btn add-btn6">
                 今日の名言
                 </button>
                 <li class="text6 text"></li>
             </div>
              
         </section>
         <section class="reset-sec clearfix">
        <div class="text-box">
            <button type="" class="delete-btn1">
                reset
            </button>
            <ul>
                <li class="text"></li>
            </ul>
        </div>
        <div class="text-box">
            <button type="" class="delete-btn2">
                reset
            </button>
            <ul>
                <li class="text"></li>
            </ul>
        </div>
    </section>

         </div>
      <!-- <div class="check"></div> -->


    <div id="third">
      <!-- コンテンツ -->
       <h1>YOUTUBE動画</h1><br>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/3hUpXwoA_Ls" frameborder="0" allowfullscreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/3qwJCcDnVdw" frameborder="0" allowfullscreen></iframe>
      <iframe width="400" height="300" src="https://www.youtube.com/embed/_dizgcnl3Vs" frameborder="0" allowfullscreen></iframe>
      <!-- <div class="check"></div> -->
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <%= javascript_include_tag 'scripts/jquery.parallax-1.1.3.js' ,'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'scripts/jquery.localscroll-1.2.7-min.js' ,'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'scripts/jquery.scrollTo-1.4.2-min.js' ,'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'script.js' ,'data-turbolinks-track': 'reload'%>
    <%= javascript_include_tag 'today.js' ,'data-turbolinks-track': 'reload'%>
  </body>
</html>

app/views/posts/fuku.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>TAIKI</title>
</head>
<body>
<iframe width="560" height="315" src="https://www.youtube.com/embed/4g28It3B6Pk" frameborder="0" allowfullscreen></iframe>
<br>
<a href="http://taiki-terminal-archives.blog.jp/">TAIKI公式ブログ</a>
<ul>
<li>ダンスを始めたきっかけ</li>
<li>モチベーション</li>
<li>ダンスを始めた頃にぶちあたった壁</li>
<li>それをクリアする為にした事</li>
<li>ずばりダンスとは！</li>
<li>お気に入りのもの</li>
<li>これからダンスを始める方に</li>
</ul>
</body>
</html>

app/views/posts/hikaru.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>hikaru</title>
</head>
<body>
<iframe width="560" height="315" src="https://www.youtube.com/embed/4g28It3B6Pk" frameborder="0" allowfullscreen></iframe>
<br>
<a href="http://taiki-terminal-archives.blog.jp/">TAIKI公式ブログ</a>
<ul>
<li>ダンスを始めたきっかけ</li>
<li>モチベーション</li>
<li>ダンスを始めた頃にぶちあたった壁</li>
<li>それをクリアする為にした事</li>
<li>ずばりダンスとは！</li>
<li>お気に入りのもの</li>
<li>これからダンスを始める方に</li>
</ul>
</body>
</html>

app/views/posts/history.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>hisutori-</title>
</head>
<body>
<iframe width="560" height="315" src="https://www.youtube.com/embed/4g28It3B6Pk" frameborder="0" allowfullscreen></iframe>
<br>
<a href="http://taiki-terminal-archives.blog.jp/">TAIKI公式ブログ</a>
<ul>
<li>ダンスを始めたきっかけ</li>
<li>モチベーション</li>
<li>ダンスを始めた頃にぶちあたった壁</li>
<li>それをクリアする為にした事</li>
<li>ずばりダンスとは！</li>
<li>お気に入りのもの</li>
<li>これからダンスを始める方に</li>
</ul>
</body>
</html>

app/views/posts/index.html.erb
<h1>info</h1>
<% @posts.each do |post| %>
  <!-- <p>タイトル</p> -->
  <span><%= link_to post.title, "/posts/#{post.id}" %></span><br>
<% end %>
<% if !current_user.blank? %>
	<%= link_to "新規投稿",posts_new_path %>
<% end %>

app/views/posts/nana.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>NANA</title>

</head>
<body>
⚪︎自己紹介⚪︎
<p>私はアイデアが自信があって、もの作りが好きですが、クリエイティブで働いた実績はありません。<br>
テレアポの方では表彰状をいただいたりランキング１位になったりはしていました。<br>
とにかく強みは努力です！！</p>
<p>２０１６年１１月にコピーライター養成講座にいき、基礎クラスは修了いたしまた。
金の鉛筆は一本だけ受賞いたしまた。４５人中で１０位以内にはいってもらえました。<br></p>
<p>２０１５年６月にはABCクッキングでパンのライセンスを取得致しました。<br>
今はダンスに夢中で毎日通っています。<br>
SNSはすべて非公開にしてますのでダンスブログを作ったものを載せます<br>
企画系から興味があります。<br></p>
どんどん吸収していきたいので宜しくお願い致します。
</br>

	デモサイト<br>
	<%= link_to "ダンスチームのサイト", "https://infoblog08.herokuapp.com/" %><br>

	ページリンクの中は適当な文で完全ではありません<br>
<br>
	掲示板はRuby on Railsで作ってます
<br>
	制作期間　約一週間
<br>
	github　heroku
<br>
<br>
<br>
	<%= link_to "ダンスブログ", "http://ameblo.jp/nananohouse" %>
	<br>
	<!-- <img src="../../assets/images/trs.jpg"> -->
	<%= image_tag '/trs.jpg' %>

</html>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

<h1>新規投稿</h1>
<%= form_tag posts_path do %>
タイトル
<p>
<input type ="text" name="title"><br>

<% if @post.errors.any? %>
	<%= @post.errors.messages[:title][0] %>
<% end %></p>
本文
<textarea name="body"></textarea>
<!-- <input type="submit" value="投稿する"＞ -->
<button type="submit">投稿する</button>

	

<% end %>

app/views/posts/omichi.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>TAIKI</title>
</head>
<body>
<iframe width="560" height="315" src="https://www.youtube.com/embed/4g28It3B6Pk" frameborder="0" allowfullscreen></iframe>
<br>
<a href="http://taiki-terminal-archives.blog.jp/">TAIKI公式ブログ</a>
<ul>
<li>ダンスを始めたきっかけ</li>
<li>モチベーション</li>
<li>ダンスを始めた頃にぶちあたった壁</li>
<li>それをクリアする為にした事</li>
<li>ずばりダンスとは！</li>
<li>お気に入りのもの</li>
<li>これからダンスを始める方に</li>
</ul>
</body>
</html>

app/views/posts/page.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Cache-Control" content="no-cache">
    <title></title>
    <link rel="stylesheet" href="css/style.css">
    
  </head>
<body>



<div class="sample4Wrap">
	<div class="sample4">Lorem ipsum dolor sit amet.</div>
</div>
<div class="box"></div>
<div class="box"></div>
<div class="box"></div>
<div class="box"></div>


<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<script type="text/javascript" src="js/script.js"></script>




</body>
</html>

app/views/posts/show.html.erb
<h2>タイトル</h2>
<p><%= @post.title %></p>
<h2>本文</h2>
<p><%= @post.body %></p>

<%= link_to "一覧へ", root_path %>

app/views/posts/taihei.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>TAIHEI</title>
</head>
<body>
<iframe width="560" height="315" src="https://www.youtube.com/embed/4g28It3B6Pk" frameborder="0" allowfullscreen></iframe>
<br>
<a href="http://taiki-terminal-archives.blog.jp/">TAIKI公式ブログ</a>
<ul>
<li>ダンスを始めたきっかけ</li>
<li>モチベーション</li>
<li>ダンスを始めた頃にぶちあたった壁</li>
<li>それをクリアする為にした事</li>
<li>ずばりダンスとは！</li>
<li>お気に入りのもの</li>
<li>これからダンスを始める方に</li>
</ul>
</body>
</html>

app/views/posts/taiki.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>TAIKI</title>
</head>
<body>




<iframe width="560" height="315" src="https://www.youtube.com/embed/4g28It3B6Pk" frameborder="0" allowfullscreen></iframe>
<br>
<a href="http://taiki-terminal-archives.blog.jp/">TAIKI公式ブログ</a>
<ul>
<li>ダンスを始めたきっかけ</li>
<li>モチベーション</li>
<li>ダンスを始めた頃にぶちあたった壁</li>
<li>それをクリアする為にした事</li>
<li>ずばりダンスとは！</li>
<li>お気に入りのもの</li>
<li>これからダンスを始める方に</li>
</ul>



</body>
</html>